services:
  _defaults:
    public: true
    autowire: true

  # Fixers
  Symplify\CodingStandard\Fixer\ArrayNotation\ArrayListItemNewlineFixer: ~
  Symplify\CodingStandard\Fixer\ArrayNotation\ArrayOpenerAndCloserNewlineFixer: ~
  Symplify\CodingStandard\Fixer\ArrayNotation\StandaloneLineInMultilineArrayFixer: ~
  Symplify\CodingStandard\Fixer\Annotation\RemovePHPStormAnnotationFixer: ~
  Symplify\CodingStandard\Fixer\Annotation\DoctrineAnnotationNestedBracketsFixer: ~
  Symplify\CodingStandard\Fixer\Commenting\RemoveUselessDefaultCommentFixer: ~
  Symplify\CodingStandard\Fixer\LineLength\LineLengthFixer: ~
  Symplify\CodingStandard\Fixer\LineLength\DocBlockLineLengthFixer: ~
  Symplify\CodingStandard\Fixer\Naming\StandardizeHereNowDocKeywordFixer: ~
  Symplify\CodingStandard\Fixer\Spacing\SpaceAfterCommaHereNowDocFixer: ~
  Symplify\CodingStandard\Fixer\Spacing\NewlineServiceDefinitionConfigFixer: ~
  Symplify\CodingStandard\Fixer\Spacing\StandaloneLinePromotedPropertyFixer: ~
  Symplify\CodingStandard\Fixer\Spacing\MethodChainingNewlineFixer: ~
  Symplify\CodingStandard\Fixer\Commenting\ParamReturnAndVarTagMalformsFixer:
    arguments:
      $malformWorkers: []

  # Coding Standard Services
  Symplify\CodingStandard\DocBlock\UselessDocBlockCleaner: ~
  Symplify\CodingStandard\Fixer\Strict\BlankLineAfterStrictTypesFixer: ~
  Symplify\CodingStandard\ValueObjectFactory\DocBlockLinesFactory: ~
  Symplify\CodingStandard\TokenAnalyzer\DoctrineAnnotationNameResolver: ~
  Symplify\CodingStandard\TokenAnalyzer\DoctrineAnnotationElementAnalyzer: ~
  Symplify\CodingStandard\TokenAnalyzer\FunctionCallNameMatcher: ~
  Symplify\CodingStandard\TokenAnalyzer\SymfonyClosureAnalyze: ~
  Symplify\CodingStandard\TokenAnalyzer\SymfonyClosureAnalyzer: ~
  Symplify\CodingStandard\TokenAnalyzer\ChainMethodCallAnalyzer: ~
  Symplify\CodingStandard\TokenAnalyzer\NewlineAnalyzer: ~
  Symplify\CodingStandard\TokenRunner\Analyzer\FixerAnalyzer\ArrayAnalyzer: ~
  Symplify\CodingStandard\TokenRunner\Analyzer\FixerAnalyzer\IndentDetector: ~
  Symplify\CodingStandard\TokenRunner\Traverser\ArrayBlockInfoFinder: ~
  Symplify\CodingStandard\TokenRunner\Transformer\FixerTransformer\LineLengthTransformer: ~
  Symplify\CodingStandard\TokenRunner\Transformer\FixerTransformer\LineLengthResolver: ~
  Symplify\CodingStandard\TokenRunner\Transformer\FixerTransformer\TokensInliner: ~
  Symplify\CodingStandard\TokenRunner\Transformer\FixerTransformer\FirstLineLengthResolver: ~
  Symplify\CodingStandard\TokenRunner\ValueObjectFactory\LineLengthAndPositionFactory: ~
  Symplify\CodingStandard\TokenRunner\Wrapper\FixerWrapper\ArrayWrapperFactory: ~
  Symplify\CodingStandard\TokenRunner\Analyzer\FixerAnalyzer\BlockFinder: ~
  Symplify\CodingStandard\TokenRunner\Transformer\FixerTransformer\TokensNewliner: ~
  Symplify\CodingStandard\TokenRunner\Transformer\FixerTransformer\LineLengthCloserTransformer: ~
  Symplify\CodingStandard\TokenRunner\Analyzer\FixerAnalyzer\TokenSkipper: ~
  Symplify\CodingStandard\TokenRunner\Transformer\FixerTransformer\LineLengthOpenerTransformer: ~
  Symplify\CodingStandard\TokenRunner\Whitespace\IndentResolver: ~
  Symplify\CodingStandard\TokenRunner\Analyzer\FixerAnalyzer\CallAnalyzer: ~
  Symplify\CodingStandard\TokenRunner\TokenFinder: ~

  # PHP CS Fixer services
  PhpCsFixer\WhitespacesFixerConfig: ~
  PhpCsFixer\Tokenizer\Analyzer\NamespaceUsesAnalyzer: ~
